# Generated by Django 4.1.3 on 2022-11-28 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id_details', models.AutoField(primary_key=True, serialize=False)),
                ('color_details', models.CharField(max_length=50)),
                ('weight_details', models.IntegerField(default=0)),
                ('size_details', models.CharField(max_length=1)),
                ('height_details', models.DecimalField(decimal_places=2, max_digits=3)),
                ('width_details', models.DecimalField(decimal_places=2, max_digits=3)),
                ('depth_details', models.DecimalField(decimal_places=2, max_digits=3)),
            ],
            options={
                'verbose_name': 'Detalle',
                'verbose_name_plural': 'Detalles',
            },
        ),
    ]
