# Generated by Django 4.1.3 on 2022-11-28 01:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id_category', models.AutoField(primary_key=True, serialize=False)),
                ('name_category', models.CharField(max_length=100)),
                ('descriptions_category', models.CharField(blank=True, max_length=100, null=True)),
                ('image_category', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id_product', models.BigAutoField(primary_key=True, serialize=False)),
                ('sku_product', models.CharField(max_length=10)),
                ('qr_product', models.CharField(max_length=10)),
                ('name_product', models.CharField(max_length=100)),
                ('price_product', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('descriptions_product', models.CharField(blank=True, max_length=100, null=True)),
                ('brand_product', models.CharField(blank=True, max_length=50, null=True)),
                ('image_product', models.CharField(blank=True, max_length=100, null=True)),
                ('create_date', models.DateField(auto_now_add=True)),
                ('stock_product', models.IntegerField(default=0)),
                ('id_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.detail')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id_seller', models.AutoField(primary_key=True, serialize=False)),
                ('name_seller', models.CharField(max_length=40)),
            ],
            options={
                'verbose_name': 'Vendedor',
                'verbose_name_plural': 'Vendedores',
            },
        ),
        migrations.CreateModel(
            name='Product_Category',
            fields=[
                ('id_product_category', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.category')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='id_seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.seller'),
        ),
    ]
